version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: thursday
    groups:
      python:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
    groups:
      gh-actions:
        patterns:
          - '*'
